# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fuzzy_winner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('tempCode', models.CharField(max_length=250)),
                ('date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
